# The ip address and port number of wakame's web api
web_api_location: '127.0.0.1'
web_api_port: 9001

# The wakame host node id or host pool id that instances should be started in.
host_node_id: 'hp-demonet'

# The wakame network id or network pool id for instances to be started in.
network_pool_id: 'nw-demonet'

# The maximum instances that can be started in one RunInstances request
max_instances_to_start: 5

# If set to true, the adapter outputs the parameters of any post requests for debugging purposes.
verbose_requests: false
